language: python
python:
    - 2.7

notifications:
    email: false

env:
  - ANSIBLE_VERSION=2.3.1.0
  - ANSIBLE_VERSION=2.2.3.0

before_install:
  - pip install tox
  - pip install ansible==$ANSIBLE_VERSION

script:
    - tox
